Hw02 express
MariOkner/nodejs-homework-rest-api pull request #1
Opened 2023-01-12 21:28 UTC by MariOkner

Please review.....

2023-01-13 12:11 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-01-13 12:11 UTC, KhYulian commented on app.js
> +  }
можна скоротити використовуючи ||

2023-01-13 12:11 UTC, KhYulian commented on app.js
> +// });
Цей комент справді потрібний?

2023-01-13 12:11 UTC, KhYulian commented on controllers/controller.js
> +    // return next(HttpError(404, "Not found!!!!!"));
Видаляйте увесь непотрібний закоментований код

2023-01-13 12:11 UTC, KhYulian commented on controllers/controller.js
> +  res.json(contact);
Додайте try catch в усі контроллери. В catch ввикликайте next і передавайте помилку next(error)

2023-01-13 12:11 UTC, KhYulian commented on controllers/controller.js
> +    // return res.status(400).json({ message: "missing required name field" });
Для цього у вас є Joi

2023-01-13 12:11 UTC, KhYulian commented on controllers/controller.js
> +  }
Аналогічно використовуйте Joi

2023-01-13 12:11 UTC, KhYulian commented on helpers.js
> +}
Використовуйте класи https://javascript.info/custom-errors

2023-01-13 12:11 UTC, KhYulian commented on schemas/contacts.js
> +});
створіть також схему для оновлення контакту

2023-01-13 12:12 UTC, KhYulian commented
Відповідайте на коменти по мірі виправлення :)

2023-01-14 23:50 UTC, MariOkner commented on app.js
> +// });
fixed

2023-01-14 23:51 UTC, MariOkner commented on controllers/controller.js
> +    // return next(HttpError(404, "Not found!!!!!"));
fixed

2023-01-14 23:51 UTC, MariOkner commented on controllers/controller.js
> +  res.json(contact);
fixed

2023-01-14 23:51 UTC, MariOkner commented on controllers/controller.js
> +    // return res.status(400).json({ message: "missing required name field" });
fixed

2023-01-14 23:51 UTC, MariOkner commented on controllers/controller.js
> +  }
fixed

2023-01-14 23:51 UTC, MariOkner commented on schemas/contacts.js
> +});
fixed

2023-01-14 23:51 UTC, MariOkner commented on helpers.js
> +}
fixed

2023-01-14 23:52 UTC, MariOkner commented on app.js
> +  }
fixed

2023-01-15 07:31 UTC, KhYulian approved these changes
Чудова робота :)

2023-01-15 07:32 UTC, merged